name: Run tests on any Push event
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: coverage run test_lab_2_digital_culture.py
      - name: Tests report
        run: coverage report
      - name: Archive file
        uses: actions/upload-artifact@v2.3.1
        with:
          name: build
          path: main
